### ISSUE TITLE
Website dramatically out of date

### ISSUE THREAD

**Issue by lino-levan** [mattfbacon/website3#1]
The information presented on this website is no longer up to date to your personal GitHub profile. I recommend keeping it up to date using some sort of CI/CD technology.

Additionally, the website is written in HTML4 and even proclaims this. This is bad practice as web browsers have been and continue to be optimized for HTML5.

Additionally additionally, you mention that users should change their default font family
> Psst... Does this site look ugly? Try tweaking your default font family.

While this is a bold (and novel) approach, I think it is fundamentally incorrect. The biggest struggle of web developers is that different browsers and different users have different engines and default styling. Leaving this to the user is bad UX and generally results in poor satisfaction.

I hope you take these critiques, not as a measure of your self worth, but as little things to help you improve in your web development journey :)

Cheers!

**Comment by mattfbacon** [comment]
>  no longer up to date

Such as?

> website is written in HTML4 ... optimized for HTML5

It is not written in HTML4 (check the doctype). It is simply compatible with it.

> users should change their default font family ... Leaving this to the user is bad UX

If it's good enough for Wikipedia, it's good enough for me.

**Comment by lino-levan** [comment]
Hey Matt,

First of all, I would like to thank you for the quick reply!

> Such as?

I would like to apologize for making assumptions, but given your current Github profile, I assumed that the following was out of date:
- You have moved from VSCodium to VSCode
- Header jumping (moving from an h1>h3 skipping h2 is bad for accessibility)
- The GIFs used on the website
- The GIFs not having an explicit width and height (to help with performance)

> It is not written in HTML4 (check the doctype). It is simply compatible with it.

Yup, that's fair, my bad. Personally believe that letting styling happen through semantic elements is dangerous and once again not good for UX.

> If it's good enough for Wikipedia, it's good enough for me.

Two things here:
- You aren't wikipedia (not having to scale to billions of visitors means you have more freedom as a designer over an engineer)
- You could still USE default fonts, but switching to something like `sans-serif` (like wikipedia) would be nice.

Overall, I imagine this website does what it is meant to achieve, but little tweaks like this could make it just that little bit better!

**Comment by lino-levan** [comment]
Just wanted to add a small thing here to clarify my font thing:

Wikipedia DOES use non-browser-default fonts
- Headers: `'Linux Libertine','Georgia','Times',serif`
- Body: `sans-serif`
- Code: `monospace`

**Comment by mattfbacon** [comment]
This is actually not the current repo for the site. Oops
